apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "terraform-20260313110452607000000001.ctwcgyikc1n3.eu-north-1.rds.amazonaws.com"
  DB_NAME: "feedbackdb"
  DB_USER: "dbadmin"